# 原則、原則、原則！

## 法治國原則

- 自主：國家不受他國干涉，個人為自己負責
- 平等：合乎實質＋形式平等，憲法第六條
- 分權：行政、司法不獨攬，眾院分權制衡
- 法定：法律明文規定規範
- 比例：自主、平等、分權保持平衡

## 罪刑法定原則
「行為之處罰，以行為時之法律為限」
防止刑法濫用以保障個人權益

1. 程序面：無罪推定
2. 實體面：無法律無犯罪，無犯罪無處罰 <br>
	1.禁止適用習慣法<br>
	2.禁止類推適用<br>
	3.回溯禁止<br>
	4.明確性<br>
3. 判斷點在「行為當時」，只要行為人不滿足行為時法之構成要件就不罰。

## 禁止習慣法

與民法有別，刑法禁止「直接」以習慣法作為法源 ex:洗門風

### 間接作為法源
例：建築危險罪(刑193)之建築術成規

1. 明文規定：建築法、建築技術成規

2. 未明文規定：建築師公會之行規

  + 主觀如法律般的位階
	
  + 客觀被整個行業遵守
  
>刑§193：<br>
承攬工程人或監工人於營造或拆卸建築物時，違背建築術成規，致生公共危險者，處三年以下有期徒刑、拘役或九萬元以下罰金。

### 因習慣法而免除行為則任

例：挖掘墳墓罪(刑249)

某甲依循撿骨之習俗，刨開墳墓，取走亡母遺骨，即使滿足其不法構成要件，不過某甲之舉是主觀承認、客觀遵守之習慣，因可免除行為責任。

>刑§249<br>
I：發掘墳墓而損壞、遺棄、污辱或盜取屍體者，處三年以上十年以下有期徒刑。<br>
II：發掘墳墓而損壞、遺棄或盜取遺骨、遺髮、殮物或火葬之遺灰者，處一年以上七年以下有期徒刑。

## 類推適用禁止

類推適用：將一未明文規定之事項(ABD)比附援引有相同基礎之法條(ABC)並加以適用。

### 加重竊盜罪

321-6之目的應為「人多的地方易發生竊盜」

即使百貨公司亦屬人多的地點，但不得依其與321-1-6等法條有相同之基礎而將在百貨公司竊盜類推適用加重竊盜罪

>I：犯前條第一項、第二項之罪而有下列情形之一者，處六月以上五年以下有期徒刑，得併科五十萬元以下罰金：<br>
6.在車站、港埠、航空站或其他供水、陸、空公眾運輸之舟、車、航空機內而犯之。

### 行為人有利之類推適用

民法之類推適用補足法律未能涵蓋之處使法官有辦法解決紛爭
而刑法之「罪刑法定」是為避免任意擴而侵害行為人。
因此，對行為人有利之類推不在禁止之列

## 回溯禁止

行為時不處罰、刑法較輕，不得回溯處罰或加重其刑罰。

<table>
  <tr>
    <th style="width:20%">溯及類別 </th>
    <th style="width:40%">以年金為例</th>
    <th style="width:40%">改變類型</th>
  </tr>
  <tr>
    <td>真正溯及 </td>
    <td>返還過去已領之年金</td>
    <td>已發生的改變</td>
  </tr>
  <tr>
    <td>不真正溯及</td>
    <td>未領取之年金</td>
    <td>未發生之改變</td>
  </tr>
</table>

例：追溯權時效變更<br>
1. 刑法施行法：8-1<br>
追溯權比較修法先後之條文採對行為人最有利的。<br>
2. 若某甲犯罪後藏匿50年，超過刑80規定之追溯年限，即使事後增修年限，不得回溯以起訴某甲

>刑法施行法§8-1<br>
於中華民國九十四年一月七日刑法修正施行前，其追訴權或行刑權時效已進行而未完成者，比較修正前後之條文，適用最有利於行為人之規定。於一百零八年十二月六日刑法修正施行前，其追訴權或行刑權時效已進行而未完成者，亦同。

