# 罪責

## 有責性

罪責的有無，即是根據行為人的違法行為是否**具有主觀的可非難性**。因此，罪責的非難對象就是行為人在違法行為當中所展現出的**主觀偏差意念**。

### 不法與罪責之區別

<table>
  <tr>
    <th width = 50%>不法</th>
    <th width = 50%>罪責</th>
  </tr>
  <tr>
    <td>構成見要件該當性+違法性</td>
    <td>主觀之可非難性</td>
  </tr>
  <tr>
    <td>行為人的行為與規範相對立衝突的狀態</td>
    <td>行為人有無能力承擔不法行為的責任</td>
  </tr>
</table>


### 罪責原則

刑罰乃是以罪責為基礎，正所謂無罪責即無刑罰，當行為人之行為具備不法時，亦要同時存在罪責才構成犯罪<br>
現行雙軌製的脈絡下，保安處分以**行為人之社會之危險性**取代罪責。部分缺乏罪責的行為會可交由保安處分，例如對罹患精神疾病之行為人施加監護措施。

罪責之成立，建立在行為人有**自由意思**之前提。即其在自由狀態下，正確判斷並辨別合法與不法的能力。<br>
而這裡的自由意思(狀態)究竟為何，非討論之重點。

## 罪責理論

### 心理罪責論(舊說)

此學說認為**罪責存在於行為人對於行為的主觀心理關係**，即所謂「知」與「欲」的心理情狀。<br>
將罪責切割成故意與過失，故意、過失本身就是罪責

此理論已經過時，原因如下：

1.**無法解釋欠缺責任能力者為何不具罪責問題**，因爲精神精神殘障或兒童仍有可能做出完全知與欲的行為。<br>

2.**忽略其他罪責要素**，如寬恕罪責的緊急避難雖為有知有欲的故意行為，但本身無罪責可言。

在目前犯罪階層理論，ㄧ率將故意、過失列入主觀構構成要件或不法層次處理。

### 規範罪責論(通說)

此學說認為**罪責之本質在於意思決定及意思活動之可非難性**，亦即不在於心理狀態(故意、過失)本身，而在於對該心理狀態所為的規範上之非難評價，影響所及，諸如責任能力、不法意識、寬恕罪責事由...皆是影響罪責判斷的要素。

### 法非難性：

1.期待可能性：一個人之所以可以被處罰，是因為我們可以**期待他不作違法之行為**。

【案例 10-2：劣馬脫韁案】<br>
19世纪未，德國發生一起馬車撞傷行人的家件。肇事的馬性格顽劣<br>
受僱的馬車夫雖知此車難以駕駛，但因迫於困苦的生活而不敢為抗主人命令，而後馬而失控撞人
馬車夫及雇主被以過失傷害罪起訴。<br>
此案中，時代因素下，我們難以期待馬車夫能為抗主人命令，而做出合法行為。因此事後之過失傷害馬車夫無罪責。


但期待可能性過於空泛，**不止可以適用有責性，也可以適用於不法性(構成見要件該當性+違法性)**<br>
例1：交通意外中，只要行為人符合四面八方的注意義務並且遵守交通規則，要求其閃避違規之行人明顯欠缺期待可能性。<br>
例2：在緊急避難的情況下，行為人為防止侵害而欠缺期待可能性

2.**他行為能力**：行為人有為合法行為的能力，卻仍舊做違法的行為

3.**反應能力**：一個人在客觀上規範有反應能力，能做出合法行為而不做。

## 不法要素

### 責任能力

判斷行為人是否具有判斷不法的辨識能力，並依此辨識而為行為的控制能力<br>
而有無責任能力是事實上之判斷，非價值判斷，我國依形式(§18-年齡）、實質（§19-辨識能力與控制能力)，區分為**完全、限制、無責**3種責任能力

**完全責任能力**：生理年齡滿18未滿80，無特殊之心裡、生理、精神障礙者

**減輕責任能力**：<br>
1.14~18歲 or >80歲 <br>
2.19II所言因精神障礙或心智缺陷導致辨識能力**顯著見低**<br>
3.刑20之瘖啞人

**無責任能力**：<br>
1.年齡 < 14歲 <br>
2.19I所言因精神障礙或心智缺陷導致辨識能力**完全欠缺**

>刑§19：<br>
I：行為時因精神障礙或其他心智缺陷，致不能辨識其行為違法或欠缺依其辨識而行為之能力者，不罰。<br>
II：行為時因前項之原因，致其辨識行為違法或依其辨識而行為之能力，顯著減低者，得減輕其刑。<br>

>刑§20:<br>
瘖啞人之行為，得減輕其刑。


### 不法意識

行為人**對於其行為之不法性的意識或意識可能性**。行為人有知有欲實現不法構成要件，通常就會知道行為乃法所不容。若沒有特別的事證，通常直接推定其具有不法意識。

不法意識之成立，並不須個案之行為人確切知道處法的規範，或其行為可罰性之必要，只需知其行為乃法所不容許。

此外，不管是潛在或事實上的不法意識，皆不排除其對違法性之認識，唯有未認識其不法意識乃出於**不可避免的禁止錯誤**下，排除罪責之分難。

>刑法16:<br>
除有正當理由而無法避免者外，不得因不知法律而免除刑事責任。但按其情節，得減輕其刑。

例：任意拿走別人的東西佔為己有，不可以主張不知該行為是竊盜罪而欠缺不法意識。(非正當理由)

例：再尋求律師的專業法律意見後，完成該律師認為合法的行為，但事後被判定抵觸法律，此時才是所謂不可避免的禁止錯誤，無罪責成立。(正當理由)


### 欠缺寬恕(或減輕)罪責事由

在罪責寬恕的方面，指行為之不法內涵在某種情況、原因、行為人之動機下大幅降低，使其低於直得處法之最低界線，而放棄對行為人做罪責非難。

這種減免不法及罪責內涵之**寬恕罪責事由**，常見於過當必難、過當防衛、公務員遵守違法命令與義務衝突等情形

以不法內涵降低的觀點來看，可非難性的降低是「程度」問題，若降低至可處法之界限以下，故然成立寬恕罪責事由。不過若降低的程度不足，仍具有可非難性，則視情況論是否為**減輕罪責事由**。<br>
例：我國刑法明定過當避難與過當防衛可能為寬恕或減輕罪責(刑23但、24I但)


:::box

Recap：**過當防衛**

> 刑§23但書：「但防衛行為過當者，得減輕或免除其刑」

典型的防衛過當是指：<br>
1、行為人主觀上出於防衛意思<br>
2、客觀上具緊急防衛情狀<br>
3、**使用了超過必要性之防衛手段(必要性與適合性)**

關於權利濫用，照理論上屬防衛過當，然而，防衛行為若以到了「濫用」之程度，**通常難以主張減免罪責的防衛過當**

而何種類型的手段可免除其刑或減輕其刑，大致分為：<br>
**不知覺**的防衛過當 -> **欠缺期待可能性** -> **寬恕罪責**的過當防衛<br>
**有知覺**的過當防衛 -> **有意選擇較重之手段** -> **減輕罪責、不法程度降低**

Recap：過當避難

**刑§24I但：避難行為過當者，得減輕或免除其刑**<br>
依此脈絡，過當避難本身不阻卻違法，但影響罪責。

典型的過當避難指：<br>
1、行為人主觀上出於避難意思<br>
2、客觀上具緊急危難<br>
3、**避難手段超過必要性(適合性or並非最小手段)**<br>
或**不符利益權衡**要求

與正當防衛之權利濫用相比較，雖然**利益權衡**亦屬客觀要件，但不符合利益權衡之過當避難，**仍可能通過非難可責性之罪責觀點**，視其程度而仍得有罪責減輕、免除之可能。

:::

<br>

現行通說承認的超法規阻卻違法事由-義務衝突，**很類似於避難過當**。<br>
但是避難過當乃兩法益發生衝突，與義務衝突有所不同。

在救生艇案中，泡水之遇難者拼命想跑上救生艇，但救生艇以滿員，承載多一個人都將導致救生艇翻覆，為了活命，將欲跑上來之乘客打昏。<br>
案件中，兩生命法益發生衝突，因不符利益衡量原則，不得阻卻違法。<br>
但我們不能期待每個人犧牲自己的生命法益拯救他人。<br>
因此在罪責面符合**寬恕罪責的事件**，依**刑24I阻卻罪責**。


## 原因自由行為

何謂原因自由行為？指**行為人因故意或過失使自己陷入無責任能力狀態，且在該狀態下實現了某個犯罪構成要件**。例如在吸毒或喝酒的狀況下，犯下殺人罪。

討論原因自由行為之重要性在於其本身並不符合**行為與罪則同時存在原則**。行為人在施行犯罪行為時確實以陷入無責任狀態，以罪責原則之脈絡下，行為與罪責必須同時存在，若強行予以定罪，恐有違反罪刑法定原則。

## 處罰根據

不管是哪種法理基礎，都是同樣的結論，但是每個理論在推倒的過程中有些瑕疵。

以下討論我國推崇之例外模式與德國之構成要件模式

### 例外模式

指**原因自由行為乃構成同時原則的例外**，行為人於意思自由的狀態下，基於特定法益侵害之目的，選擇以可受非難之方式剝奪自己的駕馭能力。

至於承認例外的形式法源何在？
有一說認為立法已經間接承認原因自由行為的處罰，並不違反罪刑法定原則。<br>
也有認為例外模式可依仗刑法第19條，將原因自由行為例外處理。

### 構成要件模式

例外模式直接連接「實行後行為」，將其視作同時原則之例外<br>
反之，構成要件模式則將「原因前行為」放在構要件的一環和罪責非難的重點，自然不把原因前行為視為例外的一種。構成要件模式又可細分為**前置理論**與**間接正犯理論**

### 前置理論

在意識狀態正常之下的自陷行為或導致無罪責行為本身便**具備可責難性**，將著手的時間往前提至原因前行為，因為該行為開啟構成要件實現的因果鏈。

相關批評：

1.「第一階段行為」便是實現構成要件的行為 這樣的因果不再是自然因果關係 而是**規範上的因果關**係，具備歸責的角度

->僅是解釋問題

2.**定式犯罪**與**不定式犯罪**的構成要件認定困難，讓**著手**跟**預備**犯區分困難<br>
以殺人罪為例，將導致每個在喝酒的人都已經屬於殺人著手<br>
以醉態駕駛為例，必須有**駕駛**行為，若有一人欲飲酒後駕車，在其飲酒前就說他在已著手駕駛，顯然相當荒謬。

->混淆預備與著手，由其在**定式行為**


### 間接正犯理論

:::box
Recap：

間接正犯：透過資訊落差、權勢高低或組織性權利機器使人完成己所欲之犯罪
己手犯與間接正犯為矛盾之概念，因此得成立間接正犯即不會成立己手犯。

例：醫生調包針劑，使護士在不知情之情狀下將有毒物質助於患者體內至其死亡。
:::

<br>

在普通間接正犯的架構下，是以利用者、被利用者與被害者三方組成。<br>
而在原因自由行為案件當中，利用者與被利用者皆是同一人，即**有責任的我利用無責任的我**
實現犯罪。

例：清醒的醫生將自己灌醉，上手術台將有毒物質助於患者體內至其死亡。

相關批評： 

**親手犯的適用困難**：

例：在肇事逃逸案例中，駕駛甲撞到行人，委託副駕乙下車查看，乙為了讓假繼續趕路而偷偷將倒在地上的行人視而不見，並矇騙假沒事，要求繼續開車。此案中乙用意識支配全局，但因爲肇事逃逸乃己手犯，乙並不負肇事逃逸刑責，而甲缺乏遇見之可能，也不罰。

放在原因自由行為的脈絡下，甲將自己灌醉，並在缺乏責任狀態下撞人並肇事逃逸，並不能以間接正反論，因爲清醒之甲並非己手，己手的甲屬於無責。

### 故意原因自由行為

故意原因自由行為必須為:

1.原因前行為乃故意所為<br>
(故意酗酒)

2.在原因前行為之際就決定要做出特定的犯行<br>
(酗酒時就想打算戒酒殺了甲)

故意原因自由行為必須兩要件同時存在，缺少一塊就缺乏內在連結性，沒有內在連結性難以對行為人為罪責非難。

### 過失原因自由行為

**故意+過失**：<br>
藉酒壯膽，想殺死仇人甲，開車開到一半昏睡撞死路人

**過失+故意**：<br>
去夜店慶祝考完試，不小心喝到同學的酒，在酒醉的情況下駕車回家，不巧遇到班上第一名，一腳油門輾斃．

**過失+過失**<br>
去夜店慶祝考完試，不小心喝到同學的酒，在酒醉的情況下駕車回家，開車開到一半昏睡撞死路人

學說上都是成立過失犯，因為過失之著手時間點與故意犯本身就有所不同。<br>
以上述3案為例，其3者皆成立過失致人於死罪，因為過失犯在違反注意義務時就已經開始著手。

但現在的實務上會把過失+故意的狀況拿出來談。<br>
依據19III，若是因為故意或過失的導致前兩項，將無前兩項之適用<br>
回到案例上，行為人因為過失導致喝醉，將不以無責任能力論處，因此採故意殺人罪。


**相關批評**

老師認為「過失＋故意」此類型應該在過失之脈絡下論處，用刑19-III以故意論有評價過度之嫌。

我國刑法對於自醉後，沒有故意也沒有遇見可能性之犯罪並無適當之處罰，因為我國在實務上在刑§19-III限縮，原因後行為也必須為故意或過失。<br>
例：一男子每次喝完酒後，都會沒有意識的睡在廁所馬桶上，他本人與親戚都對他的行為不以為意，只覺得有些好笑，但某天甲酒醉後，竟跑到鄰居家性侵隔壁鄰居得逞。<br>
實務上他有故意自醉，但其後行為沒有故意也沒有遇見可能性不罰。

在德國法律中，特別立法處理的自醉下的原因自由行為，以彌補自醉後之無責犯罪漏洞。


**修法方向**

1.限縮19-III，將過失拿掉，並且限制於兩行為有內在連結性

2.補充德國刑法323a，補足自醉行為無法處法的漏洞。

>德國刑法323a條：<br>
「行為人因可歸責於自己的事由（因故意或過失服用酒類或麻醉 藥品），致自陷於麻醉之狀態，並在此狀態下實現了任一違法行為，而因其處於麻醉狀 態下致不具罪責能力或不能排除其無罪責能力之狀態者，處五年以下有期徒刑或罰金。」


## 補充

### 過去實務見解

>實務見解【28年上字3816】：<br>
舊刑法第32條關於不得因酗酒而免除刑事責任之規定，已為現行刑法所不採，故如被告於尚未飲酒之先，即已具有犯罪之故意，其所以飲酒至醉，實欲憑藉酒力以增加其犯罪之勇氣者，固不問其犯罪時之精神狀態如何，均應依法處罰。假使被告於飲酒之初，並無犯罪之意圖，祇因偶然飲酒至醉，以致心神喪失，或精神耗弱而陷於犯罪，即難謂其心神喪失之行為仍應予以處罰，或雖係精神耗弱亦不得減輕其刑。

早期修法時將「不得因酗酒而免除刑事責任之規定」去除，並在實務見解中提及「若兩行為無內在連結性(故意＋故意)，就應得依規定減輕或免除其刑」。似乎否定了自醉相關之過失原因自由行為<br>
但目前實務見解認為對過失原因自由行為有遇見可能，就還是應論罪。


### 案例演練：


:::box
【千杯不醉案】<br>
甲駕車返家，行使途中路經一家小吃店，喝了五罐啤酒、一瓶高梁酒和吃了幾疊小菜後，再度上路。接近晚上九點三十分時，甲身懷醉意在道路上蛇行駕駛，撞上兩部正常靠右邊行駛的腳踏車騎士乙、丙，二名騎士當場死亡，事後測得甲發生事故時的血液酒精濃度值達千分之3.2。試問甲之刑事責任？

>提醒：喝酒不一定會無責!


甲之醉態駕車行為應違反刑法(下同)276過失致死罪，原因如下

1.甲之醉態駕車行為在客觀上造成乙、丙之死亡，在主觀上，喝醉酒上路為預見其能發生而確信其不發生，因爲有認識之過失。<br>
就事後客觀審查，乙與丙之死亡，確因甲之蛇行駕駛所引起，並足以發生死亡之結果。<br>

2.甲之行為並不具備任何阻卻違法要件，具備違法性無疑<br>

3.甲之行為屬酒醉造成，其乃故意陷入自醉，而後陷入無責能力撞死兩被害人。依據刑法第19-III，因故意或過失自行招致者，不適用前兩項規定，因此甲不因陷入酒醉狀態而能減輕或免除其罪責

結論：甲之行為與乙死亡之結果具有相當之因果關係、在主觀上具備有認識過失並為故意陷入自醉，無法排除其罪責，應負刑法276條之故失殺人罪。

:::

<br>

:::box

例題演練2：

甲欲至乙於死地，某日找乙共飲，欲藉酒裝瘋趁機幹掉乙，甲果真如願殺死乙，事後測得案發時甲血液酒精濃度達3.3毫克，已達到心神喪失之狀態。試分析甲之刑事責任。

甲之殺人行為應違反271-I故意致死罪，原因如下

1.主觀上，其對殺人之事早有預謀，可預見並且具備殺害乙之故意。<br>
客觀上，甲持刀殺死之行為確為乙死掉之不可想像其不存在之條件，並且引起與實現乙生命法益的風險，造成丙死亡之結果。

3.甲之行為並不具備任何阻卻違法要件，具備違法性無疑

4.甲之行為應屬原因自由行為，其乃故意陷入自醉，而後陷入無責能力殺死兩被害人。依據刑法第19-III，因故意或過失自行招致者，不適用前兩項規定，因此甲不因陷入酒醉狀態而能減輕或免除其罪責，並且兩行為有內在連接性，因此甲不因陷入酒醉狀態而能減輕或免除其罪責。

結論：甲之行為與乙死亡之結果有條件因果關係，在客觀上亦具風險實現之關聯性；在主觀上具被殺人之故意並為故意陷入自醉，ˋ視為故意原因自由行為，無法排除其罪責，應負刑法71-I故意致死罪。

:::

<br>

:::box

例題演練3：

甲獨居山中，地勢荒僻，絕少人跡。月黑之夜，甲獨斟獨飲，不覺飄飄然恍兮惚兮，醉之極矣。甲步履蹣跚，身體如風之擺柳，拿起鐮刀亂舞，吆喝不斷。此時，有登山迷路的乙，循聲走近甲的立身處，正欲出聲發問，卻遭鐮刀掃中頸部，甲則渾然未察。翌日清晨，甲酒醒，發現陌生人倒臥血泊中，已無生命跡象。試問甲之刑事責任。

請嘗試回答：<br>
刑法第十九條第一項和第二項規定，行為人於行為時，若因身心因素導致其辨識其行為違法或依其辨識而行為之能力有欠缺或顯著減低時，分別予以不罰或減輕其刑之法律效果。同條第三項規定：「前兩項規定，於因故意或過失自行招致者，不適用之」。請析論第三項規定之優缺利弊。(104高考三等刑法1)


優點：<br>
在現行第19條之規定下，對於處罰原因自由行為之第一階段為故意或過失之行為提供形式上的法源依據，我國刑法可依據例外原則讓其直接與第二階段之實際犯罪行為產生連結。

但其依然有其短處：<br>
在實務上，19-III對第二階段之行為加以限縮，若第二階段行為缺乏可預見性與故意，則將陷入無法可罰之荒唐局面。以題幹為例，雖題目中甲為故意陷入自醉之情況，但其殺死乙之行為欠缺遇見可能性，既非故意也非過失之原因自由行為，在我國刑法上不受19-III排除，而依19-I項免除其罪責。

:::