# 不作為犯

純正不作為犯：在分則裡面寫明，以不作為構成犯罪構成要件

不純正不作為犯：基於特殊身分(法律上有防止結果發生的義務)，而以不作為形式完成犯罪構成要件，又依第15條，分成3種不同的類型。

>刑法§15<br>
Ｉ:對於犯罪結果之發生，法律上有防止之義務，能防止而不防止者，與因積極行為發生結果者同。<br>
II：因自己行為致有發生犯罪結果之危險者，負防止其發生之義務。

本章節討論純正不作為犯的構成要件，與相關的判斷標準。

## 構成要件

- 主觀構成要件：是否具備故意要素？是否與客觀要素對應？

- 不作為：依前述，判斷的標準應是「風險實現的終點手段為不作為」

- 有結果之發生

- 準因果關係：ㄧ種假設性的因果關係，**如果保證人有盡其義務，則結果不會發生**。

- 作為可能性：「必須是能防止而不防止」，即保證人在危險發生當下，要具備防止行為的可能。

- 保證人地位：最為關鍵且具爭議之點，學說上有「形式法律義務理論」與「實質的保證人地位」。

- 不作為與不作為等價(過時)


### 形式法律義務理論

根據契約、條文、法律規定等產生的義務。

但有法律規定，就ㄧ定有保證人地位嗎？反之，沒有法律義務，就沒有保證人地位嗎？

1.夫妻之間，有沒有保證人對地位

民法上，夫妻之間互負扶養義務，並且雙方以「婚姻契約」締造法律上的關係。在情理上，理想的情人間應互相扶持照顧。

在某些婚姻狀況中，兩人的婚姻早就名存實亡，但迫於現實、情感等，未能離婚。兩人之間，仍是法律上的夫妻。某天，ㄧ方瀕死存亡，向對方求救，但另一方選擇見死不救，在這樣的案例下，從形式的觀點，夫妻之間具備保證人地位，但實質上，兩人之間在主觀上欠缺為對方承擔之義務，也已分開多年，視為保證人地位似乎不妥。

反之，情侶間，尚未訂立婚約，但同居多年，感情和睦生死相依，當一方因意外生死垂危，另一方有救助能力，但選擇已不作為的方式任由其死亡。以形式法律義務來說，情侶間並無法律上的義務，但實質上，兩人之間的情感關係，與生活展現出的扶持事實，雙方應為對方承擔義務，應視為保證人地位。

2.子女對父母的扶養義務

依刑法294-1，某些情形下，子女可免除其「扶養義務」，如早年父親因外遇而拋家棄子，那「救助義務」呢？在法律上，保護義務似乎無法排除，似乎可以延伸至救助義務。但實質上，不管是子女對父母，或父母對子女，皆必須要有**客觀的承擔義務事實**，與**主觀上承擔的意願**，才是所謂的保證人地位。

>刑法§294-1<br>
對於無自救力之人，依民法親屬編應扶助、養育或保護，因有下列情形之一，而不為無自救力之人生存所必要之扶助、養育或保護者，不罰：<br>
一、無自救力之人前為最輕本刑六月以上有期徒刑之罪之行為，而侵害其生命、身體或自由者。<br>
二、無自救力之人前對其為第二百二十七條第三項、第二百二十八條第二項、第二百三十一條第一項、第二百八十六條之行為或人口販運防制法第三十二條、第三十三條之行為者。<br>
三、無自救力之人前侵害其生命、身體、自由，而故意犯前二款以外之罪，經判處逾六月有期徒刑確定者。<br>
四、無自救力之人前對其無正當理由未盡扶養義務持續逾二年，且情節重大者。

3.以契約為基礎的保證人地位？

登山嚮導因臨時出車禍，無法參與登山，取消登山活動，但登山客執意登山，不料出了山難，對嚮導求救，此時嚮導若未救援，是否屬於不作為犯？以契約來說，嚮導確實要保證登山客的安全，具備保證人地位。但實質上，嚮導並未同往，也已表明其主觀上沒有承擔義務之意願，應非保證人。

反之，保母在尚未簽訂契約前，替他人照顧小孩，不料一時疏忽，導致小孩從高處跌落。以形式法律義務說，未經過契約之簽訂，保母應不具備保證人地位。但實質上，保母在答應替人照顧小孩，並且也付諸行為時，應視為主觀上有承擔意願並且具備承擔事實，為保護人。

\pagebreak

### 實質的保證人地位

在眾多理論中，最有道理的應為**控制支配說**，也就是在前面章節所提及。

**保護類型的保證人地位**，對法益的無助狀態有支配，父母對子女的安危狀態有責任，這是出於子女對**自己的生命身體法益**無法完全的保護，如嬰兒無法自己去看醫生，中小學生缺乏自主的經濟與生活能力。

同樣的，保母對嬰幼兒之安危狀態有責任，除契約上的義務，也出於嬰幼兒不具備生命身體法益的控制能力。

在各種領域中，保母、登山領導、潛水教練等等，行為人將其生命身體法益託付由相對人，於是行為人對其法益處於無助狀態，相對人則成為**法益之保護人**，對法益的侵害有責任。

**監督類型的保證人地位**，則對應**風險來源有支配**，危險來源可能是建築、天氣、交通、甚至是人。

精神病院中，具備攻擊性的病人，其醫生或監管者，在其義務範圍內，對該病人所產生的任何危險，皆有責任，以其對於該病人的行為有支配性。

遊樂園的場主，在明知設施未良好保養，仍以盈利目的營運，同於釋放其可支配之危險。此兩例皆是行為人對特殊生活領域的控制，而成為**法益之監督人**，繼而對法益的侵害有責任。

### 危險前行為保證人地位

車禍中，行人倒臥血泊中，駕駛下車查看後，選擇不做任何救治，逃之夭夭。

除了我們最喜歡的肇事逃逸之外，這樣的不作為(救治)，可能擴充至不作為犯。有學說認為，駕駛人在撞倒他人後，對該倒地之人具**生命法益的支配性**，也就是所謂的**危險前行為人保證地位**。與前兩者有別，危險前行為保證人是在「**危險發生當下才具備支配性**」。

但也有學說反對危險前行為人具備保證人地位，德國有「單純的不作為犯」，因此在處理上，以加重條文處罰此種「危難是不救助行為人造成的情形」。我國則有認為，應以鼓勵之方式，對「過失致傷者，若負起救助義務，應減輕其刑責」。

產品製造人責任-產品回收責任：(德國案例)<br>
民法上，產品製造人不只要回收問題產品，也要負「警告義務」，有認為此類情形屬於危險前行為保證人地位。若產品出現問題，一件或兩件各案下，產品製造人不算有違反注意義務，但若產品出現大量瑕疵，若未負起回收警告義務，此是屬於「未盡**監督義務**」，也就是對危險來源之控管負義務。

\pagebreak

### 等價條款

在形式法律義務理論中，許多情形會過度延伸保證人地位的適用，因此需要在以「等價」來做第二條件來輔助判斷。**但在現代朝向實質保證人地位的趨勢下，等價條款逐漸邊緣化**，轉而有「定式行為考慮等價條款之說法」。

非定式行為，不用思考等價條款，如殺人罪，不需在意不作為與作為之間是否等價。

定式行為，如詐欺罪，須以「詐術為限」。通說認為，店員在收銀時，找錯錢，與所謂「積極的誆騙」不等價。但，以實質保證人地位來說，店員本不具備任何的現實支配，何必討論等價問題。

公立醫院為了留住醫生，會支付不離開基金，而後醫生偷偷在外接案。首先，醫生對醫院「整體的財產」不具備保證人地位。但其對「激勵獎金」具備掌控地位，其默默領受獎金一事，應屬於不作為之詐欺，此類判斷也不需考慮等價條款。

### 故意

當保證人「誤以為其非保證人」之情況，是否應該成立不作為犯？

1.對「地位」的誤認：

ㄧ小孩掉入池塘中，其父親經過，但誤以為不是自己的孩子，屬於「對犯罪事實產生誤認」，也就就是**構成要件錯誤**，阻卻構成要件之故意，而依其情況判斷是否成立過失。


2.對「義務」產生誤認：

知道落水的是自己的小孩，但誤以為監護權歸前配偶，自己沒有保證人義務。此時，屬於「法律上的誤解」，也就是**禁止錯誤**，依其可避免與不可避免而阻卻或減輕刑責。

## 阻卻違法事由：等價義務衝突

僅限定在兩個作為義務情形發生下，才出現的阻卻違法事由。

例：海嘯來臨，母親眼看兩個小孩子被孩水淹沒，又僅能拯救其一。此時，母親對於未能救助之小孩，所形成之不作為，應可依此超法規阻卻違法事由，而無違法性。

## 不作為著手時點理論

- 第一救助機會說：未為「第一個」救助可能性

如醫生在第ㄧ次診療後，初判病人無需立即手術，未料病人之隱疾相當特殊，隔天突然病情急轉直入危急，轉往他國醫生給予幫助，錯過第一此機會的醫生成立殺人未遂？

**並非所有法益皆必須於第一時間救助**，如上述例子，醫生即使能救助而選擇延後救助，是出於不會對生命身體法益侵害之評估，若因此成立殺人未遂，未免荒謬

- 最後救助機會說：未為「最後一個」救助可能性

如醫生以其醫學專業，隱瞞情敵之病情，未將「5週內未服用5次就會死掉」之藥物交付給病人，未料在第3次未服用時病人主動轉診。此案，最後救助機會是「第5週最後一天」，醫生僅為預備？

**過於延遲判定，將法益陷入危險時歸為預備**，上例之醫生在好幾次不作為後，病人之生命法益幾乎已危及生命法益，仍視為預備顯不合理。

- **主客觀混和說**：法益受到具體危險＋行為人主觀犯罪計畫已至著手

如不立即救助之醫生的著手時點，既非第一次救助機會，也非病人瀕死之際，而是醫生不救助行為已危害病患生命，並且醫生對其不作為已得以致其死亡有認識。

在此，通說與一般犯之著手採同樣立場，**依行為人主觀認識，其不救助行為極可能導致客觀上法益受侵害的緊急危險**，即為著手。

比較特殊的例子，如母親欲餓死寶寶，選擇將其放置在家裡，出國旅遊。此類「放任因果歷程者」，在其放任因果流程運作後(離家)，就應當視為著手。若孩兒在母親預計出遊的第一天被發現而即時被救護，母親仍應依刑法第15條之不作為成立殺人未遂罪。


### 案例判斷

1.救生員眼看遊客溺水而不予救助

先依其主觀認定，若其主觀明知其不為救助，遊客將陷於危難，客觀上遊客之生命法益亦已遭受具體危險，此時視而不見的救生員即已著手，若其他遊客出手救助，救生員仍應依不作為成立殺人未遂罪。

2.母親棄嬰

母親不欲在養育其幼兒，主觀上明知嬰兒無法在森林中獨自存活，客觀上放任各種危險(餓死、被吞掉、被毒死)逼近，即**特別主觀認知**，即使放下嬰兒之時刻還未有危險，其份任因果流程之發生即可視為著手。

## 中止未遂

不作為犯並無區分既了未遂與未了未遂的實益，因為不作為之中止，必定是有「行動」。過去區分兩者的實益在於對**防止積極度**的要求，而不作的中止犯，**ㄧ定是積極預防**。

如護士本欲以「不施打藥劑之不作為」殺死病人，未料該計畫早已被其他護士打破，三日不見病人死亡之護士放棄原先計畫，此為**失敗未遂**。

同樣的情況，適用於作為犯的準中犯規定裡應同等適用於不作為犯身上。


## 犯罪參與問題

- 不會成間接正犯與教唆犯

間接正犯必須以己意控制犯罪流程，教唆則起碼要有「積極的教唆行為」，兩者皆非不作為能做到。

- 可能成立共同正犯或幫助犯

消極的不為其義務，如母親同意放任他人殺害自己的孩子

**特別注意保證人身分犯，不論以何種形式參與犯罪(作為、不作為)，均成立正犯！**









