# 共犯

以故意操縱犯罪流程者，為正犯，反之，對犯罪流程欠缺支配性者，稱為共犯。又依型態再分為**故意招致他人之故意犯罪決意之教唆犯**，與**故意幫助他人為故意犯罪的幫助犯**。

## 共犯從屬性?

ㄗㄨㄥˋ：附和的，陪同的

所謂共犯從屬性，指**共犯的客觀行為**，應**從於正犯的實行行為而處罰**

學說上對**從**的範圍有所不同，多數學說與我國實務，多採取**限制之從屬性說**，若正犯的行爲**非不法**(構成要件不該當或具備阻卻違法事由)，共犯的行為亦不成罪。反之，若為正犯之減輕或免除罪責事由，不會適用在共犯上。

這樣的適用相當合理，若行為人之構成要件未合制，或正犯行為符合「正當防衛」，他人之幫助或教唆行為成罪。反之，教唆**無責任能力或有排除、解除刑罰事由**者，不應享有刑法上的優惠甚至不罰。

這樣的從屬性還是會有漏洞存在，如利用行為人特質，使構成要件不合制，舉例而言，自殺不構成殺人罪，教唆或幫助他人自殺者，不會因此成立教唆或幫助殺人罪。又例如，湮滅刑事證據罪，必須為是他人的證據，教唆或幫助者，也難成立此罪之共犯。

解決這樣的情況，透過**共犯正犯化**的立法技術，也就是將幫助或教唆的**共犯行為**，當成一個**獨立犯罪**，如我國有**加工自殺罪**的條文將教唆、幫助自殺的行為獨立成罪。

### 連鎖共犯

1.共犯從屬性下，**共犯永遠必須從屬於正犯**。<br>
本質上，**沒有教唆犯的教唆犯**，都是**正犯的教唆犯**。

2.不法興層次，由大到小，後共犯僅成立**小於或等於**前共正犯的型態。<br>
教唆犯後共犯，僅會是教唆或幫助。幫助犯後共犯，僅可能是幫助犯。


## 未遂犯

### 教唆行為

教唆行為沒有特定形式，只要**足以影響他人意志**即可。有能是以金錢利誘、動之以情、誘騙等。

最為典型之教唆是從「無」到「有」，也有可能是**使他人意志堅定**(60到100)。惟，必須是**不確定到確定**，若是**確定到更確定**(100到150)，僅為**精神幫助犯**。

而教唆他人**行更為嚴重之罪**，依**既遂之重罪成立教唆**。比較有意思的是，若教唆(勸戒)他人行更輕之罪(侵害法益較低)，屬於**降低風險而欠缺客觀可歸責性**。


### 教唆他人之犯罪故意

教唆必須具備**雙重故意**，第一是**教唆行為本身是出於故意**，第二是**實行者必須為故意犯罪**。

首先，若教唆行為本身不具備故意，也就是本來沒有要喚起某種犯罪決意，如「好想讓這人死」、「找機會給他個教訓」等(打嘴砲)行為，不是教唆犯匡列之對象。

其次，針對本罪犯行，是唆使他人為「特定」且「既遂」犯罪之故意

- 特定要求：犯罪的基本輪廓

包含「特定行為人」、「特定被害人」、「特定犯罪構成要件」

正例：A女指定B男殺死C女

反例：A女叫B男去殺人

- 既遂要求：必須是有達到「既遂」之意欲。

若希望行為不既遂、不完成，不會成立既遂。

### 教唆唆與間接正犯

間接正犯之不法內涵高於教唆犯，因其對犯罪之支配性與地位高於教唆犯。換句話說，間接正犯之工具人是盲目的，可能出於(事實或法律)錯誤被其操縱。教唆犯所教唆者具有對整個犯罪計畫與行動具備支配性與自主性。

例1：A為B之上司兼老師。一天A之仇人被送入A與B之醫院。A想趁機至其仇人於死，但其為資深之醫生，若親自動手恐被看破手腳，於是以實驗為由請B進行高風險手術，果然使其仇人死亡；<br>
全案中，B因信任A而進行對仇人不利之手術，完全受A之蒙蔽，B具備完全支配性，成立殺人之間接正犯。

例2：若A以加薪為誘餌，說服B假借高風險手術失手殺死仇人，B權衡利弊後同意。;<br>
相較例1，B具備足夠之自主性，是殺人行為支配者，A僅為教唆者。


## 幫助犯要件

>刑法§30<br>
I：幫助他人實行犯罪行為者，為幫助犯。雖他人不知幫助之情者，亦同。<br>
II：幫助犯之處罰，得按正犯之刑減輕之。

幫助犯是整個二元正犯共犯體系中，不法內含最低的犯罪型態，依限制從屬性說，應依附在一「故意違法行為」，並提供「精神」或「物資」上之幫助，但缺乏對「犯罪流程之支配性」，與共同正犯有別。

### 幫助行為


所謂幫助之行為，指使正犯**得以或易於實現犯罪構成要件**，或**使正犯構成更大法益損害之犯罪貢獻**。

而幫助之形式既可以為**作為**，或**不作為**，以不作為形式成立幫助犯，必須具備**保證人地位**。

幫助犯之時點，通說認為，只要對犯罪行為予以助力，就算是**事後**，也可以成立「相續幫助犯」。而實務(95台上6081，99台上2043)，否認犯罪實行行為後，給予幫助者，可成立幫助犯。(除法律另有處罰規定外，不成立幫助犯)

\pagebreak

### 幫助犯之雙重故意

幫助犯之雙重故意與教唆犯之雙重故意無異，也就是**幫助人出於故意**，而**所幫助之罪也必須是故意犯罪**。

- 幫助犯必須知其行為足以幫助他人實現犯罪構成要件，因此出於疏忽而幫助犯罪構成者(過失)，不會成立過失幫助犯。例如，身為警察之T臨時將槍枝放在桌上，被O拿走，並且朝其仇人X開槍，T並非幫助犯，僅依其情形成立過失犯。

- 幫助犯如同教唆犯，必須是對特定犯罪有既遂故意，但不需如教唆犯般具體。


## 中性幫助行為

中性幫助行為，指日常行為而幫助犯罪。如賣刀具給欲自殺之人，提供專業知識給逃漏稅之業主，媒體、網站放置欄位供詐騙廣告放置，提供住所給逃犯等等。

這些幫助行為，無疑至少增長法益侵害可能性。幫助犯，**不需處於犯罪流程之關鍵地位**，因此即使中性行為幾乎皆具「可取代性」，也不因此免於幫助犯之責，問題在於，其邊界與討論層次？

第一，有些幫助行為已是**獨立之正犯**，如賣木炭給欲自殺之人，應討論的是「加工自殺罪(§275II)」，獨立檢驗構成要件。反之，賣刀給殺人犯，就應以殺人之幫助犯討論。

第二，應特別檢驗「製造法所不容許之風險」與「行為人之特殊認知」。前者是針對幫助行為本質上是否為「刑法意義之風險」，如賣刀、賣車、租屋等行為，就客觀層面而言，皆無製造法所不容許之風險。後者，屬於客觀歸責的例外，幫助者對正犯之犯罪計畫若得知，則其行為即**脫離日常行為範疇**，應視為幫助犯。

## 因果關係

就幫助行為是否對犯罪行為具有因果關係，尚存在爭議。

比較兩說而言，肯定說更具說服力。即幫助行為必須對犯罪之實現有一定之因果貢獻，否則有擴張刑法之疑慮。特別注意的是，幫助既可以是物質幫助，也可以是精神幫助。如Ａ提供給欲行偷竊之B萬能鑰匙，即使B未使用，仍可能因其以提供萬能鑰匙，鞏固其犯意，而成立竊盜罪之幫助犯。