# 附錄與題目

## 罪刑法定原則

問：請列舉罪刑法定的基本內涵與延生原則。<br>
105政大轉學考第一題

::: box

::: center1
**擬答**
:::

(一)罪刑法定的基本內涵

::: indent-2
罪刑法定乃基於刑法(下同)第一條：「行為之處罰，以行為時之法律有明規定者為限。拘束人身自由之保安處分，亦同。」<br>
其意義在於限制國家刑法動用之範圍，必須以事先明定之法條為做為依據，使人民之財產、生命、自由不輕易遭到剝奪與損害，從積極面觀之，本原則避免國家濫權侵害人民之基本權，消極面發揮一般預防功能，使法成為人民行事之底線。
:::

(二)派生之原則

質法人員必須遵守「無罪推定原則」

而在實體面，分別有禁止習慣法、禁止類推適用、禁止溯及既往與明確性原則，以下分而述之。

::: indent-2
1.禁止習慣法原則
:::

::: indent-4
(1)內涵：習慣法，客觀上為大眾多年慣行之事實，主觀上對其有確信心。而刑法為最後之底線，必須避免將無明文規定之習慣法隨意加入處罰之列，給予法官造法之可，因此禁止習慣法作為直接法源<br>
但其可作為間接法源，亦可作為有利行為人之解釋。
:::

::: indent-4
(2)案例：台灣有加害者必須至被害者家門中洗門風、登報道歉等傳統之彌補傷害手段，但以上刑罰皆為習慣法而非法有明訂之刑罰，故不得以上述之習慣作為刑罰之手段。<br>
:::

::: indent-2
2.禁止類推適用
:::


::: indent-4
(1)內涵：文義有限，事實無窮，法條總難以涵蓋所有之情況，但刑法乃最嚴厲之法律，若隨意將相關之法條彼此比附援引，恐有過度擴張刑法而侵害行為人之虞。綜上所述，刑法禁止「不利於行為人之類推適用」
:::

::: indent-4
(2)案例：按刑法321第1項第6款之加重竊盜罪：「在車站、港埠、航空站或其他供水、陸、空公眾運輸之舟、車、航空機內而犯之」。<br>
觀諸其立法目的，即保護「人多」而易遭受竊盜之地。但即使符合此要件之地點，如百貨公司，只要非此條所明訂之地，不得類推適用此條法令
:::

::: indent-2
3.禁止回溯
:::


::: indent-4
(1)內涵：罪刑法定主義以「行為時」作為判斷基準，禁止回溯使行為人不遭事後設立之法加以定罪。惟依第二條第1項之但書，當事後法對行為人有利時，則可例外適用。又，行為人若為繼續犯而其行為跨越新法與舊法，惟不真正溯及既往，不在適用範圍
:::

::: indent-4
(2)案例：若行為人犯刑法320之竊盜罪，爾後加重至7年，行為人之刑責因以舊法為準<br>
反之，若立法者刪除竊盜罪，行為人應適用新規而非舊法
:::

::: indent-2
4.明確性原則
:::


::: indent-4
(1)內涵：不管是「犯罪之構成要件」或「法律效果」皆必須清楚<br>
而明確之標準有3：意義非難以了解、行為人可預見、由司法審查加以確認
:::

::: indent-4
(2)案例：缺乏要件明確性之法條如，檢肅流氓條例之「欺壓善良」、「遊檔無賴」<br>
缺乏法律效果明確性者如「應處有期徒刑」之絕對不定期行．
:::

:::

## 公務員之定義

問：甲為某市里長，受市公所囑託協助督導在該里執行社會勞動性工作，乙受法院判刑得易服社會勞動確定，經地檢署派往該里執行易服社會勞動。爾後，甲與乙產生犯意聯絡，為其之工作時數做錯誤之登載。試問甲就不實登載時數一事，是否為刑法上之公務員？


::: box

::: center1
擬答
:::

(一)甲就不實登載時數一事，非屬刑法上之公務員

::: indent-2
1.實務見解認為，依照地方制度法規定，里辦公處為各鄉、鎮、縣轄市及區等地方自治團體設各里之地方行政機關，里長於辦公時為第10條第2項第1款前段身分公務員
:::

::: indent-2
2.本文認為里長是否為公務員不得一概而論之。申延之，依民國95年公務員概念之修法意旨，應視其事務內容是否具有公權力性質或公共事務特質，以及是否有服從與照顧義務而定。
:::

::: indent-4
(1)依題幹，甲受市公所囑託協助督導該里執行社會勞動工作，並非該里本身之事務，其法定職務權限不涉及於此，非第10條二項前段所言之身分公務員
:::

::: indent-4
(2)題幹謹言「受市公所囑託」，無任何法律授權而有法定權限，當非授權公務員。
:::

::: indent-4
(3)雖甲所為之事乃公共事務，亦為受行政機關囑託而行事，但其執行事項皆受其指示而**無以自己名義對外行使職權之行政主體身分**，判斷其僅為行政輔助人，並非第10條第2項第2款之「委託公務員」
:::

(二)綜上，甲非刑法上之公務員，其登載時數不實之行為不成立第213條公務員之登載不實罪。

:::


> 最高法院 98年台上字第 7191號刑事判決：<br>
依地方制度法第二條第一款、第十四條之規定，地方自治團體係指依該法實施地方自治，具公法人地位之團體，...。村、里辦公室固非屬地方自治團體，但同法第五條第二項明定各級地方自治團體均各有其立法機關與行政機關，而依同條第四項及同法第五十九條規定，...為**地方自治團體設於各村、里之地方行政機關**，且村、里置村、里長一人，辦理村、里之公務及交辦事項，故村、**里長**自屬依法服務於地方自治團體所屬機關而具有**法定職務權限之公務員**。

>  最高法院105年台上字第1272號刑事判決：<br>
刑法第十條第二項第二款規定之委託公務員，...此所稱「依法委託」，應依法律、法律授權之法規命令、職權命令、自治條例、自治規則、委辦規則或其他對**多數不特定人民就一般事項所作對外發生法律效果之規定**為委託。又所謂「從事與委託機關權限有關之公共事務」，必其受託之公共事務與委託機關之**權限有關**，並因而於受託範圍內取得**行政主體身分**，而得**以自己名義獨立對外行使公共事務職權**；若僅係在**機關指示下，協助處理行政事務，性質上祇屬機關之輔助人力**，並非獨立之官署或具有自主地位，尚難認係刑法上所稱之委託公務員


## 準中止犯、不能未遂

某甲與乙相處不睦，一日，二人因細故爭吵，甲一氣之下決定除乙為痛快。 其向黑市購買了一斤毒藥，並將其融入水中，欲假意與乙和好使其喝下。然 而，甲因記性過差，竟誤將白糖罐錯當毒藥，乙喝下後安然無恙。甲發現自 己錯誤後更加火冒三丈，一日持棍棒至乙家門外叫囂。乙出門查看後，甲趁 機亂棒將乙打倒在地。乙之好友丙正巧路過，見狀趕忙上前幫忙，並大罵甲 是個作惡多端之人。甲聽此突幡然悔悟，連忙拿出手機打電話叫救護車。但 丙因見乙狀況不佳，便自行先駕車將乙送醫，乙因此撿回一命。試問甲之行 為應如何處斷？ 

::: box

::: center1
擬答
:::

甲下毒之行為，可能成立刑法第271條第一項之殺人未遂罪

::: indent-2
ㄧ：客觀上，乙未有死亡之結果，惟本罪論未遂，而甲主觀上具有致乙於死之故意，依主客觀混和說，甲既存在下毒行為，且認為該行為後乙應有死亡之結果，其行為應已著手。
:::

::: indent-2
二：本案之甲是否可適用中止未遂的規定減輕或免除其刑，以下分述之：
:::

::: indent-4
1.甲誤將白糖當作毒藥，客觀上顯不能導致犯罪之發生，亦未對當事人產生實際之危險，按第26條之規定，符合前項不能發生結果與又無危險兩要件。
:::


::: indent-4
2.惟甲誤將白糖當作毒藥，客觀上顯不能導致犯罪之發生，亦未對當事人產生實際之危險，按第26條之規定，符合前項不能發生結果與又無危險兩要件。然，依重大無知說，行為人尚需出於重大無知誤認自然法則，非純粹對事實產生誤認。行為人甲之行為乃因記性問題導致失手，因此不得適用第26條之規定。
:::

::: indent-2
三：依上述，甲以故意犯意而對乙下毒，且行為至著手階段，應成立刑法第271條第一項之殺人未遂罪。
:::

甲拿棍棒打乙之行為，成立刑法271第二項殺人未遂罪

::: indent-2
ㄧ：
:::

::: indent-2
二：本案之甲是否可適用中止未遂的規定減輕或免除其刑，以下分述之：
:::

::: indent-4
1.依刑法第27條第一項前半段，中止未遂之成立，必須在客觀上具備防止犯罪之行為，該行為成功防止且與結果未發生有因果關係，且出於行為人之自由意志。
:::

::: indent-4
2.本案中，甲因幡然醒悟而放棄屬出於自由意志，並且該犯罪結果未發生。而甲已先持棍毆打乙，行為應屬既遂，其積極救助行為尚稱積極，惟，乙未死亡乃因第三人丙之救助，甲打電話救助之行為欠缺因果關係，故不適用。
:::

::: indent-2
三：行為人甲得否適用準中止犯之規定，以下分述之：
:::

::: indent-4
1.依第27條第一項後半段，準中止犯之規定，結果之不發生，非防止行為所致，而行為人已盡力為防止行為者，適用中止犯之規定。於此，中止犯之成立，必須客觀上有積極防止行為，且結果為第三人或侵害客體所防止，而使救助行為與結果欠缺因果關係。
:::

::: indent-4
2.依題幹所示，甲因丙之勸說，出於己意中止毆打行為，並且已呼叫救護車之行為防止乙死亡之結果。又乙之死亡結果乃因丙之救助，與甲之防止行為欠缺因果關係，符合準中止犯之規定。
:::

::: indent-2
依上述，甲具備準中止犯所必需之積極與相當要件，應適用刑法第27條第一項後半段之規定，減輕或免除其刑。
:::

::: indent-2
四：結論

總論之，甲毆打乙之行為，可能成立刑法第271條第二項之殺人未遂罪，而甲之救助行為，應適用刑法第27條第一項後半段之規定，減輕或免除其刑。
:::

:::


### 未遂與客體錯誤

::: box

甲對丙之開槍行為，不成立刑法第271條第ㄧ項之殺人罪：

::: indent-2
ㄧ、構成要件

客觀上，存在丙死亡之結果，而甲朝其開槍行為亦足以造成該結過，惟，丙在甲開槍前已死亡，可謂甲之行為與丙死亡之結果不存在相當因果關係。
:::

::: indent-2
二、結論

依上述而言，甲之行為在構成要件之客觀審查層面難認有相當因果關係，不成立刑法第271條第ㄧ項之殺人罪。
:::

甲對丙之開槍行為，應成立刑法第277條第二項之殺人未遂罪：

::: indent-2  
ㄧ、構成要件

主觀上，甲雖存在誤認丙為乙之等價客體錯誤存在，然該誤認僅為不重要之動機錯誤，並不影響甲之故意存在。客觀上，依主客觀混和說，有甲衝進宿舍而為開槍行為，並行為人認其行為足以造成該客體死亡之結果，其為已著手犯罪實行。
:::

::: indent-2
二、惟在客觀上，甲是否得成立刑法第26條之不能未遂而不罰，以下分述之
:::

::: indent-4
1.所謂不能未遂，即行為人所為之行為既不能造成結果發生，又無危險者。依題幹，丙在甲開槍之行為前已死亡，蓋可謂甲之行為既不能造成丙死亡之結果，對死人開槍亦不存再危險性。
:::


::: indent-4
2.惟依重大無知說，不能既遂之成立，除了上述兩點外，不能造成結果之行為因出於重大無知。本案例，甲之開槍行為不能造成結果，顯非出於該行為人對事實之重大誤認，而為偶然事件導致之障礙未遂。
:::

::: indent-2
本論採重大無知說，甲不存在自然因果關係之誤認而不得成立不能未遂。
:::

::: indent-2
三、結論

總論之，甲主觀上具備上存在殺害被害人之故意，客觀其行為已處於著手階段，並且屬偶然事件而導致結果不發生之障礙未遂，不具備減輕或免除罪責事由，應成立刑法第277條第二項之殺人未遂罪。
:::

:::

### 違法性、容許構成要件錯誤

::: box
乙壓制甲之行為應不成立刑法第304條第1項強制罪：

::: indent-2

ㄧ、構成要件

客觀上，乙有壓制他人之強制行為，該行為確造成並足以使甲之自由權利受到剝奪。主觀上，乙以誤認甲將為搶劫行為而有使甲失去自由之故意。

二、違法性

違法性層面，乙主觀上認為甲為搶劫行為，而其獲得刑法第21條之依法令行為之阻卻違法事由，然，甲實際上並未有實際之犯罪行為，乙不得適用該條而阻卻違法。

三、罪責

依題幹，乙乃因A大喊「搶劫啊」且一時疏忽而誤以為有阻卻違法事由前提，學說稱之為「容許構成要件錯誤」，而其法律效果與概念在學說上有分歧，以下概述之：

:::

::: indent-4
1.依故意理論，乙誤認阻卻違法事由前提，屬於構成要件之不法意識欠缺，而在構成要件層次阻卻故意犯罪成立。

2.依二階理論，阻卻違法是由屬構成要件層次的反面要件，由此，誤認阻卻違法事由之前提，與構成要件錯誤同屬欠缺構成要件之故意而不成立故意犯。

3.依照嚴格錯誤理論，針對阻卻違法事由誤認而欠缺不法意識者，無論為誤認前提或法律事實，同屬禁止錯誤，依可避免於不可避免之錯誤，在罪責層次減輕或免除其刑。

4.依德國通說，稱類推構成要件錯誤理論，容許構成要件錯誤應比照構成要件錯誤，以主客觀不一致而阻卻構成要件故意犯罪之成立。

5.我國通說採限縮法律效果之限制罪責理論，依此理論，罪責層次與構成要件之故意應當分立，當事人應容許構成要件錯誤而為之行為，仍具備構成要件之故意，而是在罪責層次阻卻故意，屬阻卻罪責而免除該故意之刑事責任。
:::

::: indent-2
本論採我國通說，乙誤認搶劫而誤以為獲依法令行為之組卻違法事由，在罪責層次不存在故意，應阻卻故意之刑事責任。

四、結論

乙之行為具備構成要件之主觀故意與客觀行為，並無或任何阻卻違法事由，而在罪責層次免除其故意之刑事責任，不構成刑法第304條第1項之強制罪。

:::

甲踢倒乙之行為，不成立刑法第277條第ㄧ項之傷害罪：

::: indent-2
ㄧ、構成要件

客觀上，甲踢乙之行為，足以傷害其身體健康，並確實造成乙胸部挫傷之結果。主觀上，甲具備踢開乙之故意。

二、違法性

就違法性而言，甲在主觀上認為其受到不法之侵害，並且以踢擊方式完成正當防衛之行為，而在客觀情狀下，乙之壓制行為雖不成立故意之犯罪，然仍為具備主客觀構成要件之不行為，蓋甲之行為應可依刑法第23條而依正當防衛阻卻違法。

三、結論

甲之行為得依刑法第23條之正當防衛，而阻卻構成刑法第277條第ㄧ項之傷害罪。

:::

:::


